name=Validador de CPF e CNPJ
encoding=UTF-8

parameter.string.mail_smtp_socketFactory_class=javax.net.ssl.SSLSocketFactory
parameter.string.mail_transport_protocol=smtp
parameter.string.mail_smtp_host=smtp-aws.techne.com.br

maven.dependencies.resolve=true
maven.dependecies.new.dependency.1.groupId=org.apache.lucene
maven.dependecies.new.dependency.1.artifactId=lucene-analyzers-stempel
maven.dependecies.new.dependency.1.version=6.1.0

